import Head from 'next/head'
import { Grid } from '../components'

export default function HomePage() {
  return (
    <Grid>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Grid>
  )
}
