import Head from 'next/head'
import { useRouter } from 'next/router'
import { Button, Grid } from '../components'

export default function HomePage() {
  const router = useRouter();
  return (
    <Grid
      ff="column wrap"
      ai="center"
      padding="2rem 0 0 0"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Button
        onClick={() => {
          router.push(`/menu`)
        }}
      >View Menu</Button>
    
    </Grid>
  )
}
